on:
  push:
    branches: 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3

        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2

        with:
          flutter-version: "3.24.5"
          channel: "stable"

      - name: Clear Flutter cache
        run: flutter pub cache repair

      - name: Check Flutter and Dart versions
        run: |
          flutter --version
          dart --version

      - name: Get dependencies
        working-directory: app
        run: flutter pub get
